# Generated by Django 5.0.6 on 2024-05-17 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio",
            "0002_alter_stock_purchase_date_alter_stock_purchase_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="user",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.DeleteModel(
            name="Portfolio",
        ),
    ]
